import struct

ADC_V_SLOPE  =  0.00000000235714724017
ADC_V_OFFSET = -0.01390133824020600000

TEST_MODE = False

AVI_CMD_PORT   = 1234
AVI_TELEM_PORT = 25565
SYNNAX_PORT    = 9090

if TEST_MODE:
    SYNNAX_IP = 'localhost'
    AVI_IP    = 'localhost'
else:
    SYNNAX_IP = '128.46.118.59'
    AVI_IP    = '128.46.118.59'

SYNNAX_USERNAME = "Bill"
SYNNAX_PASSWORD = "Bill"

TELEM_FORMAT = '<QQQ'
TELEM_SIZE   = struct.calcsize(TELEM_FORMAT)

LOX_CHANNEL_NAME     = 'PT-OX-201_calc'
FUEL_CHANNEL_NAME    = 'PT-FU-201_calc'
HELIUM_CHANNEL_NAME  = 'PT-HE-201_calc'
BB_OPEN_CHANNEL_NAME = 'BB_OPEN_ALL_CMD'
BB_ISO_CHANNEL_NAME  = 'BB_ISO_ALL_CMD'
BB_REG_CHANNEL_NAME  = 'BB_REG_ALL_CMD'
BB_FU_UPPER_SETP_NAME = 'BB_SET_FU_UPPER_SETP'
BB_OX_UPPER_SETP_NAME = 'BB_SET_OX_UPPER_SETP'
BB_FU_LOWER_SETP_NAME = 'BB_SET_FU_LOWER_SETP'
BB_OX_LOWER_SETP_NAME = 'BB_SET_OX_LOWER_SETP'
BB_FU_UPPER_REDLINE_NAME = 'BB_SET_FU_UPPER_REDLINE'
BB_OX_UPPER_REDLINE_NAME = 'BB_SET_OX_UPPER_REDLINE'
BB_FU_LOWER_REDLINE_NAME = 'BB_SET_FU_LOWER_REDLINE'
BB_OX_LOWER_REDLINE_NAME = 'BB_SET_OX_LOWER_REDLINE'

FUEL_SOLENOID_NAME = 'SV-HE-202'
LOX_SOLENOID_NAME  = 'SV-HE-201'
